
language: python

python:
  - { PATH: "{{Python38}}", VERSION: 3.8, DIST: std, PYINT: python3.8 }
  
virtualenv:
  - path: {{ospathjoin(root_path, pickname("$NAME_JENKINS", project_name + "_$VERSION_$DIST_$NAME"), "_venv")}}
  
install:
  - $PYINT -m pip install --upgrade pip
  - $PYINT -m pip install --upgrade --no-cache-dir --no-deps --index http://localhost:8067/simple/ jyquickhelper pyquickhelper --extra-index-url=https://pypi.python.org/simple/
  - $PYINT -m pip install -r requirements.txt
  - $PYINT --version
  - $PYINT -m pip freeze
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1

before_script:
  - $PYINT -u setup.py build_ext --inplace Release
  - $PYINT -u setup.py build_ext --inplace Debug

script:
  - { CMD: "$PYINT -u setup.py unittests", NAME: "UT" }
  - { CMD: "cd cscode; dotnet test -c Release TestCSharpyCore; dotnet test -c Debug TestCSharpyCore; cd ..", NAME: "UT_CSharp" }

after_script:
  - $PYINT -u setup.py bdist_wheel
  - if [ ${VERSION} == "3.7" and ${DIST} != "conda" and ${NAME} == "UT" ] then cp dist/*.whl {{root_path}}/../local_pypi/local_pypi_server fi

documentation:
  - if [ ${NAME} == "UT" ] then $PYINT -u setup.py build_sphinx fi
  - if [ ${NAME} == "UT" ] then cp -R -f _doc/sphinxdoc/build/html dist/html fi
