dist: xenial
sudo: true
language: python
git:
  submodules: true
  
matrix:
  include:
    - python: 3.7
      env: &xplat-env
      addons: &xplat-addons
        apt:
          sources:
          - sourceline: deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial main
            key_url: https://packages.microsoft.com/keys/microsoft.asc
          packages:
            - dotnet-sdk-3.1

env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
    - PYTHONUNBUFFERED=True
    - DOTNET_CLI_TELEMETRY_OPTOUT=1

before_install:
  # Set-up dll path for embedded tests
  - PY_LIBDIR=$(python -c 'import sysconfig; print(sysconfig.get_config_var("LIBDIR"))')
  - export LD_LIBRARY_PATH=$PY_LIBDIR:$LD_LIBRARY_PATH
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1
  # Addition to build
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-5 --allow-unauthenticated
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 90
  # For python
  - python -m pip install -U pip
  - pip install -U setuptools wheel

install:
  - pip install pycparser
  - pip install -r requirements.txt

before_script:
  # Build the package
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - gcc --version
  - python setup.py build_ext --inplace Debug
  - python setup.py build_ext --inplace Release

script:
  # Copy the compiled binaries.
  - cd cscode
  - dotnet test -c Release TestCSharpyCore
  - dotnet test -c Debug TestCSharpyCore
  - cd ..
  # Runs the tests.
  - python setup.py unittests
