dist: trusty
language: python

python:
    - "3.6"

addons:
-  apt:
-    packages:
      - wget -q packages-microsoft-prod.deb https://packages.microsoft.com/config/ubuntu/14.04/packages-microsoft-prod.deb
      - sudo dpkg -i packages-microsoft-prod.deb
      - sudo apt-get install apt-transport-https
      - sudo apt-get update
      - sudo apt-get install dotnet-sdk-2.1.200

env:
  - DOTNET_CLI_TELEMETRY_OPTOUT=1

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-5 --allow-unauthenticated
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 90
  - sudo mono tools/nuget/nuget.exe update -self 
  - dotnet restore
  - pip install -r requirements.txt

before_script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - gcc --version
  - python setup.py build_ext --inplace
    
script:
    - python setup.py unittests
