dist: focal
sudo: true
language: python
git:
  submodules: true
  
matrix:
  include:
    - python: 3.9
      env: &xplat-env
      addons: &xplat-addons
        apt:
          sources:
          - sourceline: deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-focal-prod focal main
            key_url: https://packages.microsoft.com/keys/microsoft.asc
          packages:
            - dotnet-sdk-3.1
            - dotnet-runtime-5.0
            - aspnetcore-runtime-5.0
            - apt-transport-https

env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
    - PYTHONUNBUFFERED=True
    - DOTNET_CLI_TELEMETRY_OPTOUT=1

before_install:
  # Set-up dll path for embedded tests
  - PY_LIBDIR=$(python -c 'import sysconfig; print(sysconfig.get_config_var("LIBDIR"))')
  - export LD_LIBRARY_PATH=$PY_LIBDIR:$LD_LIBRARY_PATH
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1
  # For python
  - python -m pip install -U pip
  - pip install -U setuptools wheel
  # pythonnet
  - python -m pip install wheel
  - git clone https://github.com/pythonnet/pythonnet
  - cd pythonnet
  - python setup.py build_dotnet
  - python setup.py install

install:
  - pip install -r requirements.txt
cache: pip

before_script:
  # Build the package
  - python setup.py build_ext --inplace Debug
  - python setup.py build_ext --inplace Release

script:
  # Copy the compiled binaries.
  - cd cscode
  - dotnet test -c Release TestCSharpyCore
  - dotnet test -c Debug TestCSharpyCore
  - cd ..
  # Runs the tests.
  - python setup.py unittests
