dist: trusty
sudo: true
language: python
git:
  submodules: true
  
matrix:
  include:
    - python: 3.6
      env: &xplat-env
      addons: &xplat-addons
        apt:
          sources:
          - sourceline: deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main
            key_url: https://packages.microsoft.com/keys/microsoft.asc
          #- sourceline: deb http://download.mono-project.com/repo/ubuntu trusty main
           # key_url: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xA6A19B38D3D831EF
          packages:
            #- mono-devel
            #- ca-certificates-mono 
            - dotnet-sdk-2.1.200

env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
    - PYTHONUNBUFFERED=True
    - DOTNET_CLI_TELEMETRY_OPTOUT=1

#addons:
#  apt:
#    sources:
#      - sourceline: deb http://download.mono-project.com/repo/ubuntu trusty main
#        key_url: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xA6A19B38D3D831EF
#    packages:
      #- mono-devel
      #- ca-certificates-mono
#      - clang
#      - cmake
#      - libunwind8
#      - curl
      # ubuntu https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x#ubuntu
#      - libunwind8
#      - liblttng-ust0
#      - libcurl3
#      - libssl1.0.0
#      - libuuid1
#      - libkrb5-3
#      - zlib1g
#      - libicu52

before_install:
  # Set-up dll path for embedded tests
  - PY_LIBDIR=$(python -c 'import sysconfig; print(sysconfig.get_config_var("LIBDIR"))')
  - export LD_LIBRARY_PATH=$PY_LIBDIR:$LD_LIBRARY_PATH
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1
  # Addition to pythonnet build
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-5 --allow-unauthenticated
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 90
  # For python
  - python -m pip install -U pip
  - pip install -U setuptools wheel
  - set PYTHONPATH=src

install:
  # Install pythonnet
  - pip install pycparser
  - git clone https://github.com/pythonnet/pythonnet.git
  - cd pythonnet
  - python setup.py install --xplat
  - cd ..
  - pip install -r requirements.txt

before_script:
  # Build the package
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - gcc --version
  - python setup.py build_ext --inplace Debug
  - python setup.py build_ext --inplace Release

script:
  # Copy the compiled binaries.
  - cd cscode
  - dotnet test -c Release TestCSharpyCore
  - dotnet test -c Debug TestCSharpyCore
  - cd ..
  # Runs the tests.
  - python setup.py unittests
