dist: trusty
language: python

python:
    - "3.6"

addons:
  apt:
    sources:
    - sourceline: deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main
      key_url: https://packages.microsoft.com/keys/microsoft.asc
    - sourceline: deb http://download.mono-project.com/repo/ubuntu trusty main
      key_url: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xA6A19B38D3D831EF
  packages:
    - mono-devel
    - ca-certificates-mono
    - dotnet-hostfxr-2.0.0
    - dotnet-runtime-2.0.0
    - dotnet-sdk-2.0.0

env:
  - DOTNET_CLI_TELEMETRY_OPTOUT=1

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-5 --allow-unauthenticated
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 90
  - sudo mono tools/nuget/nuget.exe update -self 
  - dotnet restore

install:
  - pip install -r requirements.txt

before_script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - gcc --version
  - python setup.py build_ext --inplace
    
script:
    - python setup.py unittests
