dist: trusty
language: python
mono: none
dotnet: 2.0.0
script:
  - dotnet restore
  - dotnet build

python:
    - "3.6"
addons:
-  apt:
   - sources:
          - sourceline: deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main
            key_url: https://packages.microsoft.com/keys/microsoft.asc
          - sourceline: deb http://download.mono-project.com/repo/ubuntu trusty main
            key_url: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xA6A19B38D3D831EF   - packages:
      - mono-devel
      - ca-certificates-mono
      - dotnet-hostfxr
      - dotnet-runtime
      - dotnet-sdk
    
install:
    - sudo mono tools/nuget/nuget.exe update -self
    - pip install -r requirements.txt
before:
    - python setup.py build_ext --inplace
script:
    - python setup.py unittests
