environment:

  global:
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_compiler.cmd"

  matrix:

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%\\python -m pip install --upgrade pip"
  - "%PYTHON%\\Scripts\\pip install pymyinstall"
  - "%PYTHON%\\Scripts\\pymy_install3 --set=pyquickhelper"
  - "%PYTHON%\\Scripts\\pymy_install3 pythonnet"
  - "%PYTHON%\\Scripts\\pip install -r requirements.txt"
  - "set PATH=%PATH%;C:\\projects\\jyquickhelper\\build\\update_modules\\Graphviz\\bin"
  - set DOTNET_CLI_TELEMETRY_OPTOUT=1

build: off

before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./src/src.csproj --verbosity m

before_test:
  - "%PYTHON%\\python -u setup.py build_ext --inplace Release"
  - "%PYTHON%\\python -u setup.py build_ext --inplace Debug"
  
test_script:
  - cd cscode
  - dotnet test -c Release TestCSharpyCore
  - dotnet test -c Debug TestCSharpyCore
  - cd ..
  - "%PYTHON%\\python -u setup.py unittests"

after_test:
  - "%PYTHON%\\python -u setup.py bdist_wheel"

artifacts:
  - path: dist
    name: csharpy
