version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2-sdk
    
    working_directory: ~/repo
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: Install python (0)
          command: |
                    apt-get update
                    apt-get install -y build-essential checkinstall
                    apt-get install -y libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev
                    apt-get install -y python3-software-properties
                    apt-get install -y software-properties-common
                    python3 -V

      - run:
          name: Install python (1)
          command: |
                    apt-get install -y python3-venv python3-pip

      - run:
          name: Install pip env
          command: |
                    python3 -m pip install pipenv

      - run:
          name: Install pandoc
          command: |
                    apt-get update 
                    wget https://github.com/jgm/pandoc/releases/download/2.1.3/pandoc-2.1.3-1-amd64.deb
                    dpkg -i pandoc-2.1.3-1-amd64.deb
          
      - run:
          name: Install tex
          command: |
                    apt-get install -y texlive
                    apt-get install -y texlive-latex-extra
          
      - run:
          name: Install 7z, unrar
          command: |
                    apt-get install -y p7zip-full
          
      - run:
          name: Install InkScape
          command: |
                    apt-get install -y inkscape
          
      - run:
          name: Install graphviz
          command: |
                    apt-get install -y graphviz
          
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt            
            pip3 install scipy scikit-learn
            
      - run:
          name: install pythonnet
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -U setuptools
            pip3 install -U wheel
            pip3 install git+https://github.com/pythonnet/pythonnet.git

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          name: build extension
          env:
            DOTNET_CLI_TELEMETRY_OPTOUT:1
          command: |
            . venv/bin/activate
            python3 setup.py build_ext --inplace

      - run:
          name: run tests                  
          env:
            DOTNET_CLI_TELEMETRY_OPTOUT:1
          command: |
            . venv/bin/activate
            python3 setup.py unittests

      - run:
          name: wheel
          env:
            DOTNET_CLI_TELEMETRY_OPTOUT:1
          command: |
            . venv/bin/activate
            python3 setup.py bdist_wheel
            mkdir -p test-reports/dist
            cp dist/*.whl test-reports/dist

      - run:
          name: documentation
          command: |
            . venv/bin/activate
            python3 setup.py build_sphinx
            
      - run:
          name: copy documentation
          command: |
            mkdir -p test-reports/doc
            cp -r  _doc/sphinxdoc/build/html test-reports/doc
            
      - store_artifacts:
          path: test-reports
          destination: test-reports